package com.cubis.jasper

import java.io.File

object JasperFontExtensionManager {
    
    private val resourcesDir = File("src/main/resources")
    private val fontsXmlFile = File(resourcesDir, "fonts.xml")
    private val extensionPropertiesFile = File(resourcesDir, "jasperreports_extension.properties")
    
    /**
     * Generate fonts.xml and jasperreports_extension.properties based on registered fonts
     */
    fun generateFontExtensions() {
        val registeredFonts = FontRegistry.getRegisteredFonts()
        
        if (registeredFonts.isEmpty()) {
            println("No fonts registered, skipping font extension generation")
            return
        }
        
        // Ensure resources directory exists
        if (!resourcesDir.exists()) {
            resourcesDir.mkdirs()
        }
        
        // Generate fonts.xml
        generateFontsXml(registeredFonts)
        
        // Generate jasperreports_extension.properties
        generateExtensionProperties()
        
        println("✓ Generated JasperReports font extensions for ${registeredFonts.size} fonts")
    }
    
    /**
     * Generate fonts.xml file
     */
    private fun generateFontsXml(fonts: Map<String, FontRegistry.FontInfo>) {
        val xml = buildString {
            appendLine("<?xml version=\"1.0\" encoding=\"UTF-8\"?>")
            appendLine("<fontFamilies>")
            
            fonts.forEach { (name, fontInfo) ->
                appendLine("    <fontFamily name=\"$name\">")
                
                // Normal face
                appendLine("        <normal><![CDATA[${fontInfo.normalPath}]]></normal>")
                
                // Bold face
                fontInfo.boldPath?.let { path ->
                    appendLine("        <bold><![CDATA[$path]]></bold>")
                }
                
                // Italic face
                fontInfo.italicPath?.let { path ->
                    appendLine("        <italic><![CDATA[$path]]></italic>")
                }
                
                // Bold Italic face
                fontInfo.boldItalicPath?.let { path ->
                    appendLine("        <boldItalic><![CDATA[$path]]></boldItalic>")
                }
                
                // PDF settings
                appendLine("        <pdfEncoding>${fontInfo.pdfEncoding}</pdfEncoding>")
                appendLine("        <pdfEmbedded>${fontInfo.pdfEmbedded}</pdfEmbedded>")
                appendLine("        <exportFonts/>")
                
                appendLine("    </fontFamily>")
            }
            
            appendLine("</fontFamilies>")
        }
        
        fontsXmlFile.writeText(xml)
        println("✓ Generated fonts.xml with ${fonts.size} font families")
    }
    
    /**
     * Generate jasperreports_extension.properties file
     */
    private fun generateExtensionProperties() {
        val properties = buildString {
            appendLine("# JasperReports Font Extensions")
            appendLine("# Auto-generated by JasperReports API Service")
            appendLine()
            appendLine("net.sf.jasperreports.extension.registry.factory.simple.font.families=net.sf.jasperreports.engine.fonts.SimpleFontExtensionsRegistryFactory")
            appendLine("net.sf.jasperreports.extension.simple.font.families.custom=fonts.xml")
            appendLine()
            appendLine("# Enable headless mode for image generation")
            appendLine("java.awt.headless=true")
        }
        
        extensionPropertiesFile.writeText(properties)
        println("✓ Generated jasperreports_extension.properties")
    }
    
    /**
     * Remove font extensions (cleanup)
     */
    fun removeFontExtensions() {
        if (fontsXmlFile.exists()) {
            fontsXmlFile.delete()
            println("✓ Removed fonts.xml")
        }
        if (extensionPropertiesFile.exists()) {
            extensionPropertiesFile.delete()
            println("✓ Removed jasperreports_extension.properties")
        }
    }
    
    /**
     * Check if font extensions exist
     */
    fun hasFontExtensions(): Boolean {
        return fontsXmlFile.exists() && extensionPropertiesFile.exists()
    }
    
    /**
     * Get fonts.xml content
     */
    fun getFontsXmlContent(): String? {
        return if (fontsXmlFile.exists()) {
            fontsXmlFile.readText()
        } else {
            null
        }
    }
    
    /**
     * Get extension properties content
     */
    fun getExtensionPropertiesContent(): String? {
        return if (extensionPropertiesFile.exists()) {
            extensionPropertiesFile.readText()
        } else {
            null
        }
    }
}
